# ************************************************************
# Sequel Pro SQL dump
# Version 4096
#
# http://www.sequelpro.com/
# http://code.google.com/p/sequel-pro/
#
# Host: 127.0.0.1 (MySQL 5.5.44-MariaDB)
# Database: tdwg
# Generation Time: 2015-11-24 19:11:37 +0000
# ************************************************************


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


# Dump of table tx_tdwgbiodivprojects_networks
# ------------------------------------------------------------

DROP TABLE IF EXISTS `tx_tdwgbiodivprojects_networks`;

CREATE TABLE `tx_tdwgbiodivprojects_networks` (
  `uid` int(11) NOT NULL AUTO_INCREMENT,
  `pid` int(11) NOT NULL DEFAULT '0',
  `tstamp` int(11) NOT NULL DEFAULT '0',
  `crdate` int(11) NOT NULL DEFAULT '0',
  `cruser_id` int(11) NOT NULL DEFAULT '0',
  `t3ver_oid` int(11) NOT NULL DEFAULT '0',
  `t3ver_id` int(11) NOT NULL DEFAULT '0',
  `t3ver_wsid` int(11) NOT NULL DEFAULT '0',
  `t3ver_label` varchar(30) NOT NULL DEFAULT '',
  `t3ver_state` tinyint(4) NOT NULL DEFAULT '0',
  `t3ver_stage` tinyint(4) NOT NULL DEFAULT '0',
  `t3ver_count` int(11) NOT NULL DEFAULT '0',
  `t3ver_tstamp` int(11) NOT NULL DEFAULT '0',
  `t3_origuid` int(11) NOT NULL DEFAULT '0',
  `deleted` tinyint(4) NOT NULL DEFAULT '0',
  `hidden` tinyint(4) NOT NULL DEFAULT '0',
  `name` tinytext NOT NULL,
  `logo` blob NOT NULL,
  `website` tinytext NOT NULL,
  `description` text NOT NULL,
  `language` int(11) NOT NULL DEFAULT '0',
  `last_accessed` int(11) NOT NULL DEFAULT '0',
  `geographic_scope` text NOT NULL,
  `comments` text NOT NULL,
  `finalised` tinyint(3) NOT NULL DEFAULT '0',
  PRIMARY KEY (`uid`),
  KEY `parent` (`pid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

LOCK TABLES `tx_tdwgbiodivprojects_networks` WRITE;
/*!40000 ALTER TABLE `tx_tdwgbiodivprojects_networks` DISABLE KEYS */;

INSERT INTO `tx_tdwgbiodivprojects_networks` (`uid`, `pid`, `tstamp`, `crdate`, `cruser_id`, `t3ver_oid`, `t3ver_id`, `t3ver_wsid`, `t3ver_label`, `t3ver_state`, `t3ver_stage`, `t3ver_count`, `t3ver_tstamp`, `t3_origuid`, `deleted`, `hidden`, `name`, `logo`, `website`, `description`, `language`, `last_accessed`, `geographic_scope`, `comments`, `finalised`)
VALUES
	(40,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'Wikipedia - Botanical Gardens','','http://en.wikipedia.org/wiki/List_of_botanical_gardens','Lists important botanical gardens throughout the world',0,1190152800,'Global','',1),
	(39,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'UNEP-WCMC Environment organizations links','','http://www.unep-wcmc.org/resources/sites/index.html','United Nations Environment Programme, World Conservation Monitoring Centre links page. Wide variety of organizations with separate pages for Animals, Antarctic and Arctic, Biodiversity and conservation organisations, Coastal marine and freshwater, Conventions and Agreements, Education and resources, Environment and ecology, Forests, Plants, Policy finance and legal, Social sciences and indigenous people, Volunteer Information, Zoos and sanctuaries',0,1195426800,'Global','',1),
	(38,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'United Nations - Oceanographic NGOs','','http://www.un.org/Depts/los/Links/NGO-links.htm','United Nations list of Non-Governmental Organizations (NGO) that are concerned with the law of the sea. Additional links to lists on the same site for regional and national governmental organizations.',0,1195426800,'Global','',1),
	(36,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'Society for Range Management','','http://www.rangelands.org/links_affiliated_organizations.shtml','List with links and acronyms of organizations affiliated to the SRM',0,1190152800,'USA','',1),
	(37,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'SWED - Semantic Web Environmental Directory','','http://www.swed.org.uk/swed/index.html','SWED is the prototype for a new kind of directory of environmental organizations and projects. Rather than centralising the storage, management and ownership of the information, in SWED the organisations and projects themselves hold and maintain their own information. The information is published on their web sites. SWED simply \'harvests\' that information and uses it to create the directory. Note that the site is the result of an EU-funded project and is not maintained on a day-to-day basis. June 2007.',0,1179525600,'Global','',1),
	(35,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'Open Directory Project','','http://www.dmoz.org/Science/Environment/Organizations/','Over 600 links from Top: Science: Environment: Organizations in 18 categories, with another 500 links at Top: Society: Issues: Environment: Organizations ',0,1187474400,'Global','',1),
	(34,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'Oceanography organizations','','http://www.academicinfo.net/oceanorg.html','Lists of links for organization home pages copyrighted to Academic Info but apparently associated with the University of Phoenix.  Last Modified April 2006, as at July 2007.',0,1184796000,'Global','',1),
	(33,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'OBIS Providers, Partners and Sponsors','','http://www.iobis.org/about/','OBIS (Ocean Biogeographic Information System) information about data providers, funders and regional nodes',0,1176933600,'Global','',1),
	(32,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'Nature Societies Online','','http://internt.nhm.ac.uk/jdsml/research-curation/library/digital-library/nature-societies-online/','A database offering direct links to a wide variety of general natural history and subject specific organisations in Britain and Ireland. Local, county and national groups and societies are represented. Nature Societies Online is managed by Library and Information Services of the Natural History Museum.',0,1176933600,'UK','',1),
	(30,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'National Federation of Biological Recorders','','http://www.nbn-nfbr.org.uk/nfbr.php','List of UK local biological records centres',0,1190152800,'UK','',1),
	(31,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'Natural History Museums & Collections','','http://www.lib.washington.edu/sla/natmus.html','Museums of natural history and collections worldwide, produced by the University of Washington Libraries',0,1195426800,'Global','',1),
	(29,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'National Biodiversity Network','','http://www.searchnbn.net/organisation/organisationList.jsp','List of contributors to the UK National Biodiversity Network (NBN)',0,1195426800,'UK','',1),
	(26,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'Intute - Natural History','','http://www.intute.ac.uk/healthandlifesciences/nature/','Over 200 records about organizations in the field of botany, zoology, ecology and biology are returned by putting \"organisation\" (with an \"s\") into the search box. The returned listing includes descriptions of the organizations and ratings of their Websites',0,1195426800,'Global','',1),
	(27,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'Marine Biology Institutes','','http://life.bio.sunysb.edu/marinebio/mblabs.html','Part of the Marine Biology Web, an educational resource, listing marine biology laboratories, instituties and graduate programmes',0,1192744800,'Global','',1),
	(73,-1,1198070172,1198070172,0,28,0,0,'',0,0,0,0,0,0,0,'NBII Partners','','http://www.nbii.gov/portal/community/Communities/Toolkit/NBII_Partners/','Underpinning the National Biological Information Infrastructure\'s information network is a network of partners. Pages are listed here under the headings of US Federal; State; and Local government; International; Non-profit; Private; University and Multi-sector partners.',0,1182204000,'USA','',1),
	(25,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'Internet Directory for Botany','','http://herba.msu.ru/mirrors/www.helsinki.fi/kmus/botsoc.html','Substantial listing of international organizations in botany,  with additional headings for arobreta and botanical gardens, botanical museums,  societies, university departments etc.',0,1190152800,'Global','',1),
	(23,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'Insect and Spider collections of the World','','http://hbs.bishopmuseum.org/codens/codens-inst.html','Codens, names and some links to insect and spider collections, with search tool.',0,1190152800,'Global','',1),
	(24,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'International Zoo Educators Association','','http://www.izea.net/world/world.htm','Click on a region of the world map at this link to list the IZE Members. Each regional section contains a quarterly update and a list of regional members.',0,1187474400,'Global','',1),
	(22,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'Index Herbariorum','','http://sciweb.nybg.org/science2/IndexHerbariorum.asp','Included in the on-line edition of Index Herbariorum is information for 3,293 herbaria in 168 countries and 10,060 staff members associated with these herbaria. Information for over 80% of the herbaria has been updated, and 526 herbaria have been added since the eighth edition of INDEX HERBARIORUM.',0,1176933600,'Global','',1),
	(21,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'IUCN - see Wold Conservation Union','','','',0,0,'','',1),
	(19,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'Google Directory','','http://www.google.com/Top/Science/Environment/Organizations/','Over 1,000 organizations listed under the main heading Science: Environment: Organizations, under 18 sub-categories',0,1187474400,'Global','',1),
	(20,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'HerpNET participants','','http://www.herpnet.org/participants.html','Almost 60 organizations participate in HerpNET. Also provided in the list is the institutional acronym and whether the collection catalogue is available online.',0,1190152800,'Global','',1),
	(18,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'GBIF Data Providers','','http://data.gbif.org/datasets/','Extensive listing of organizations that provide datasets to the Global Biodiversity Information Facility ',0,1182204000,'Global','',1),
	(16,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'Fishnet 2 Partners','','http://www.fishnet2.net/partners.html','Listing of the 29 partners that belong to FishNet 2 as data providers',0,1192744800,'Global','',1),
	(17,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'Forest Conservation Links','','http://forests.org/links/Organizations/welcome.asp','Around 200 links to organizations maintained by Forests.org under the headings Advocacy; Education and awareness; Environmental law; Faith based; Foundations and funders; Networks. Each is given a star rating out of 10, with some given additional accolades such as Editor\'s pick and Popular.',0,1184796000,'Global','',1),
	(15,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'European Community Biodiversity Clearing House Mechanism','','http://biodiversity-chm.eea.europa.eu/network/other','Biodiversity organizations and networks, listed under three major headings: Global; European; National',0,1179525600,'Global','',1),
	(14,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'EnviroLink','','http://www.envirolink.org/categories.html?catid=5','Organizations are listed  under the following categories: Agriculture (161),  Air Quality (121), Climate Change (88), Ecosystems (247), Energy (167), Environmental Disasters (15), Environmental Economics (87), Environmental Education (203), Environmental Ethics (13), Environmental Legislation and Policy (166), Forests (49), Ground Pollution (86), Habitat Conservation (193), Human Health (53), Natural History (6),  Oceans (23), Outdoor Recreation (16), Population (30), Sciences (169), Social Sciences and Humanities (119), Sustainable Business (71), Sustainable Development (21), Sustainable Living (99), Transportation (23), Urban Issues (13), Vegetarianism (36), Waste Management (104), Water Quality (202), Wildlife (349). Within a category there is a one or two line description of each organization with the links taking you to a page with more information, including contact details',0,1176933600,'Global','',1),
	(13,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'Directory of Australian Botanic Gardens & Arboreta','','http://www.anbg.gov.au/chabg/bg-dir/','The Directory is endorsed by the Council of Heads of Australian Botanic Gardens (CHABG) representing the Directors of the major botanic gardens in Australia',0,1192744800,'Australia','',1),
	(12,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'Conservation Directory','','http://www.nwf.org/conservationdirectory/','Guide to the thousands of environmental non-profit, education, commercial, and government groups operating across the planet. 4,210 groups listed as of May 2007. Available online through the National Wildlfe Federation. Information is available for searching by institution, city, state, acronym, staff member, correspondent, research specialty, and important collections. Telephone and fax numbers and e-mail and URL addresses are included.',0,1179525600,'Global','',1),
	(11,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'CBOL partners','','http://barcoding.si.edu/member_organizations.html','Since the inaugural meeting in May 2004, over 130 organizations from 43 countries across 6 continents have joined the Consortium for the Barcode of Life. These are listed by continent and country and another link shows their location on Google Maps.',0,1182204000,'Global','',1),
	(10,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'Botany Organizations','','http://www.academicinfo.net/botorg.html','Lists of links for organization home pages copyrighted to Academic Info but apparently associated with the University of Phoenix.  Last Modified April 2006, as at July 2007.',0,1184796000,'Global','',1),
	(8,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'BiologyBrowser','','http://www.biologybrowser.org/bb/Subject/Organizations/Biodiversity_Organizations/index.shtml','BiologyBrowser, produced by Thomson Scientific, is a free web site offering resources for the life sciences information community. Biodiversity organizations are listed under the headings: Global networks; Museum and university biodiversity centres; National networks; State and local networks; Regional networks',0,1187474400,'Global','',1),
	(9,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'Botanique','','http://www.botanique.com/','Searchable listing of over 2700 gardens, arboreta and nature sites in the United States and Canada',0,1192744800,'North America','',1),
	(7,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'Biodiversity Organizations, Professional Societies, Centers, & Associations','','http://www.academicinfo.net/biodivorg.html','Lists of links for organization home pages copyrighted to Academic Info but apparently associated with the University of Phoenix.  Last Modified April 2006, as at July 2007.',0,1184796000,'Global','',1),
	(6,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'Best of the Web','','http://botw.org/top/Science/Environment/Biodiversity/Organizations/','A small selection of biodiversity organizations listed in the BotW directory',0,1176933600,'Global','',1),
	(67,-1,1198070172,1198070172,0,5,0,0,'',0,0,0,0,0,0,0,'BG-Base - user list','','http://rbg-web2.rbge.org.uk/BG-BASE/users.htm','As of June 2006, there are 169 sites in 26 countries using BG-BASE, ranging in size from fewer than 8 staff members to over 400 staff members, and from less than 5 acres (2 ha) to over 3,000 acres (1,215 ha). Users include botanic gardens, arboreta, university campuses, herbaria, museums, libraries, government agencies, research institutions, municipal gardens, conservation organizations, horticultural societies, private estates, zoos, and cemeteries.',0,1184796000,'Global','',1),
	(4,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'Australasian Regional Association of Zoological Parks and Aquaria','','http://www.arazpa.org.au/','ARAZPA was established in 1990 to link zoos and aquariums in Australia, New Zealand and the South Pacific in a cooperative regional network for wildlife conservation. ARAZPA now links over 70 institutions, all working together to protect and conserve the worldâ€™s wildlife.',0,1192744800,'Australasia','',1),
	(2,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'ARKive - British organizations','','http://www.arkive.org/linksBritishCBO.html','Around 20 conservation and biodiversity organizations in the United Kingdom listed by Arkive',0,1190152800,'UK','',1),
	(3,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'Association of Zoos & Aquariums','','http://www.aza.org/Accreditation/AccreditList/','AZA accredited zoos and aquariums. Name and US state only in this list.',0,1195426800,'USA','',1),
	(47,-1,1198070225,1197320649,0,44,0,0,'',0,0,0,0,0,1,0,'Zoos in Europa','','http://www.zoos.de/Europa.htm','Zoological gardens primarily in Germany, Austria, Switzerland and the Netherlands',0,0,'Europe','',1),
	(46,-1,1197407991,1197407991,81,45,0,0,'',0,0,0,0,0,0,0,'Conservation Commons','','http://www.conservationcommons.org/','The Conservation Commons is the expression of a cooperative effort of non-governmental organizations, international and multi-lateral organizations, governments, academia, and the private sector, to improve open access to and unrestricted use of, data, information and knowledge related to the conservation of biodiversity with the belief that this will contribute to improving conservation outcomes. At its simplest, it encourages organizations and individuals alike to ensure open access to data, information, expertise and knowledge related to the conservation of biodiversity. ',30,1197414000,'Global','',1),
	(45,917,1197408152,1197408152,81,45,0,0,'Info by LeeBelbin',0,0,0,1197408152,45,0,0,'Conservation Commons','','http://www.conservationcommons.org/','The Conservation Commons is the expression of a cooperative effort of non-governmental organizations, international and multi-lateral organizations, governments, academia, and the private sector, to improve open access to and unrestricted use of, data, information and knowledge related to the conservation of biodiversity with the belief that this will contribute to improving conservation outcomes. At its simplest, it encourages organizations and individuals alike to ensure open access to data, information, expertise and knowledge related to the conservation of biodiversity. ',30,1197414000,'Global','',1),
	(1,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'ARKive - Global organizations','','http://www.arkive.org/linksGlobalCBO.html','Over 100 global conservation and biodiversity organizations listed by Arkive',0,1190152800,'Global','',1),
	(41,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'Wikipedia - Botanical Gardens in the USA','','http://en.wikipedia.org/wiki/List_of_botanical_gardens_in_the_United_States','Include all significant botanical gardens and arboretums in the United States of America, by State.',0,1190152800,'USA','',1),
	(42,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'Wikipedia - Environmental organizations','','http://en.wikipedia.org/w/index.php?title=Category:Environmental_organizations','The first stop for many people for almost any information, the category on environmental organizations has 9 sub-categories and 207 individual pages.',0,1179525600,'Global','',1),
	(43,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'World Conservation Union','','http://intranet.iucn.org/kb/pub/members/directory.cfm','Searchable database of members of the IUCN. Filter by country or by status - National NGO (765 total); International NGO (83 total);  Affiliate (33 total); State (83 total); Government Agency with State Member (84 total); Government Agency without State Member (26 total) ',0,1195426800,'Global','',1),
	(44,914,1198070172,1198070172,0,0,0,0,'',0,0,0,0,0,0,0,'Zoos in Europa','','http://www.zoos.de/Europa.htm','Zoological gardens primarily in Germany, Austria, Switzerland and the Netherlands',0,1195426800,'Europe','',1),
	(48,917,1200031281,1200031281,81,0,0,0,'',0,0,0,0,0,0,0,'National Science Collections Alliance','','http://www.nscalliance.org/','The Natural Science Collections Alliance is a Washington, D.C.-based nonprofit association that supports natural science collections, their human resources, the institutions that house them, and their research activities for the benefit of science and society.\r\n\r\nOur members are part of an international community of museums, botanical gardens, herbariums, universities and other institutions that house natural science collections and utilize them in research, exhibitions, academic and informal science education, and outreach activities.',30,1225494000,'North America','',1),
	(49,917,1200032217,1200032217,81,0,0,0,'',0,0,0,0,0,0,0,'American Association of Museums','','http://www.aam-us.org/','\"AAMâ€™s mission is to enhance the value of museums to their communities through leadership, advocacy, and service.\"\r\n\r\nThe American Association of Museums has been bringing museums together since 1906, helping to develop standards and best practices, gathering and sharing knowledge, and providing advocacy on issues of concern to the entire museum community. We are dedicated to ensuring that museums remain a vital part of the American landscape, connecting people with the greatest achievements of the human experience, past, present and future.\r\n\r\nAAM is the only organization representing the entire scope of museums and professionals and nonpaid staff who work for and with museums. We currently represent more than 15,000 individual museum professionals and volunteers, 3,000 institutions, and 300 corporate members. Individual members span the range of museum occupations, including directors, curators, registrars, educators, exhibit designers, public relations officers, development officers, security managers, trustees and volunteers.\r\n\r\nEvery type of museum is represented including art, history, science, military and maritime, and youth museums, as well as aquariums, zoos, botanical gardens, arboretums, historic sites, and science and technology centers.',30,1225494000,'USA','',1),
	(50,917,1200428091,1200428091,344,0,0,0,'',0,0,0,0,0,0,0,'Semantic Annotation of Taxonomic Descriptions','','http://research.sbs.arizona.edu/gs/cgi-bin/library ','This website is established by Dr Hong Cui of the University of Arizona. Dr Cui research on semantic markup of taxonomic descriptions. Descriptions marked-up in XML format via an automated means are accessible via the website. Taxonomic descriptions of variate types and sizes [English only] are welcome to join the website. ',30,1199142000,'','',1),
	(84,-1,1205188515,1205188515,808,51,0,0,'',0,0,0,0,0,0,0,'Biodiversity Information System of Colombia','','http://www.siac.net.co/sib','The Biodiversity Information System of Colombia (SIB the initials in spanish) is a national institutional alliance created to meet information needs of the country, in order to promote the knowledge, conservation and sustainable use of biodiversity. ',112,1204498800,'National - Colombia','This network provides access to standards, controlled vocabularies (taxonomic authorities and thesauri), metadata, species descriptions and occurrences, distributed biological records, and other useful tools to assist the biodiversity information manage process.',1),
	(52,917,1223867829,1223867829,1012,0,0,0,'',0,0,0,0,0,0,0,'Species Profile and Threats Database (SPRAT)','','http://www.environment.gov.au/cgi-bin/sprat/public/sprat.pl','Detailed text profiles are provided for a range of species and ecological communities which are listed under the Australian Government\'s environment protection legislation (EPBC Act 1999). Detailed descriptions are provided for many hundreds of species and include such things as distribution, population details, life history, threats and recovery plans and comprehensive references. ',30,1223848800,'Australia','',1),
	(54,-1,1234903190,1234903190,201,53,0,0,'',0,0,0,0,0,0,0,'Canadensys','','http://www.canadensys.net','The mission of Canadensys is to unlock the specimen information held by Canadian university-based biological collections and share this via a network of distributed databases, compatible with other biodiversity information networks like CBIF and GBIF. In its initial phase, the network focuses on data of three of the most diverse, ecologically and economically important groups of organisms: plants, insects and fungi, the latter two representing some of the most poorly understood and inventoried organisms world-wide.',30,0,'Canada, Global','',1),
	(53,917,1234903438,1234903438,201,53,0,0,'Info by PeterDesmet',0,0,0,1234903438,53,0,0,'Canadensys','','http://www.canadensys.net','The mission of Canadensys is to unlock the specimen information held by Canadian university-based biological collections and share this via a network of distributed databases, compatible with other biodiversity information networks like CBIF and GBIF. In its initial phase, the network focuses on data of three of the most diverse, ecologically and economically important groups of organisms: plants, insects and fungi, the latter two representing some of the most poorly understood and inventoried organisms world-wide.',30,1234825200,'Canada, Global','',1),
	(55,917,1236842622,1236842622,34,0,0,0,'',0,0,0,0,0,0,0,'Australasian Herbarium Information Systems Committee','','http://hiscom.chah.org.au/wiki/','The Herbarium Information Systems Committee (HISCOM), established in 1995 by Council of Heads of Australasian Herbaria (CHAH), has representatives of the computing and information technology programs of each participating institution and deals with the development and application of new technologies to herbarium management, botanical research and information delivery. HISCOM\'s flagship project is the Australia\'s Virtual Herbarium. ',30,1234825200,'Australasia, Australia and New Zealand, Western Australia, South Australia, Victoria, Tasmania, New South Wales, Queensland, Northern Territory, Australian Capital Territory','Regular/Recent Participants:\r\n * Australian National Herbarium (CANB) - Greg Whitbread; Jim Croft\r\n * Western Australian Herbarium (PERTH) - Ben Richardson; Alex Chapman \r\n * State Herbarium of South Australia (AD) - Bill Barker; Paul Coddington\r\n * National Herbarium of Victoria (MEL) - Alison Vaughan, Niels Klazenga\r\n * Tasmanium Herbarium (HO) - Laurence Paine\r\n * National Herbarium of New South Wales (NSW) - Karen Wilson; Gary Chapple\r\n * Queensland Herbarium (BRI) - Peter Bostock\r\n * Northern Territory Herbarium (DNA) - Donna Lewis\r\n * Australian Biological Resources Study (ABRS) - Helen Thompson \r\n * Allan Herbarium (CHR) - Aaron Wilton, Jerry Cooper\r\n * Auckland Museum Herbarium (AK) -\r\n * Te Papa Tongarewa Herbarium (WELT) - ',1),
	(57,-1,1241163492,1241163492,1170,56,0,0,'',0,0,0,0,0,0,0,'NatureGate','','http://www.naturegate.net','Online service of wild folwers, trees and bushes, birds, butterflies and later on other organism groups. Fishes will be included during 2009. NatureGateÂ® is result of over 20 years of systematic R&D involving continuing, enlarging and deepening collaboration between professional nature photographers and university experts of the organism groups involved. NatureGateÂ® Online Service uses a patented interactive method and system for fast and easy species identification, based on location of object and its observable chacteristics.',30,1241128800,'Global. The pilot covers currently mainly European species,also invasive species and many cosmoplitan plant species. The ultimate aim is to cover all organism groups and  enlarge use of the patented method and system for interactive object recognition using locality and obervable characteristics to the whole world. Practically, it has to be realized gradually region by region, organism group by organism group. ','Focused on species level biodiversity informatics education for all people, from children to elderly people, both for professionals and amateurs. All organisms are photographed in their natural habitats, biotopes, ecosystems. There are many photos of butterflies and other insects on flowers, pollinating. Photos are of extraordinary quality. They are scientifically accurate and at the same time they creat a strong nature experience. The International Union for Conservation of Nature (IUCN) writes:  http://www.iucn.org/about/union/commissions/cec/?2614/. The Finnish Institute of Environment (SYKE), and Ministry of Environment has a descriptive link:\r\nhttp://www.ymparisto.fi/default.asp?node=5319&lan=en',1),
	(58,-1,1241163860,1241163860,1170,56,0,0,'Info by MauriAhlberg',0,0,0,1241163860,56,0,0,'NatureGate','','http://www.naturegate.net','Online service of wild folwers, trees and bushes, birds, butterflies and later on other organism groups. Fishes will be included during 2009. NatureGateÂ® is result of over 20 years of systematic R&D involving continuing, enlarging and deepening collaboration between professional nature photographers and university experts of the organism groups involved. NatureGateÂ® Online Service uses a patented interactive method and system for fast and easy species identification, based on location of object and its observable chacteristics.',30,1241128800,'Global. The pilot covers currently mainly European species,also invasive species and many cosmopolitan plant species. The ultimate aim is to cover all organism groups and  enlarge use of the patented method and system for interactive object identification using locality and obervable characteristics to the whole world. Practically, it has to be realized gradually region by region, organism group by organism group. ','Focused on species level biodiversity informatics education for all people, from children to elderly people, both for professionals and amateurs. All organisms are photographed in their natural habitats, biotopes, ecosystems. There are many photos of butterflies and other insects on flowers, pollinating. Photos are of extraordinary quality. They are scientifically accurate and at the same time they creat a strong nature experience. The International Union for Conservation of Nature (IUCN) writes:  http://www.iucn.org/about/union/commissions/cec/?2614/. The Finnish Institute of Environment (SYKE), and Ministry of Environment has a descriptive link:\r\nhttp://www.ymparisto.fi/default.asp?node=5319&lan=en',1),
	(59,-1,1241163985,1241163985,1170,56,1,0,'Info by MauriAhlberg',0,0,2,1241163985,56,0,0,'NatureGate','','http://www.naturegate.net','Online service of wild folwers, trees and bushes, birds, butterflies and later on other organism groups. Fishes will be included during 2009. NatureGateÂ® is result of over 20 years of systematic R&D involving continuing, enlarging and deepening collaboration between professional nature photographers and university experts of the organism groups involved. NatureGateÂ® Online Service uses a patented interactive method and system for fast and easy species identification, based on location of object and its observable chacteristics.',30,1241128800,'Global. The pilot covers currently mainly European species,also invasive species and many cosmopolitan plant species. The ultimate aim is to cover all organism groups and  enlarge to the whole world, use of the patented method and system for interactive object identification using locality and obervable characteristics. Practically, it has to be realized gradually region by region, organism group by organism group. ','Focused on species level biodiversity informatics education for all people, from children to elderly people, both for professionals and amateurs. All organisms are photographed in their natural habitats, biotopes, ecosystems. There are many photos of butterflies and other insects on flowers, pollinating. Photos are of extraordinary quality. They are scientifically accurate and at the same time they creat a strong nature experience. The International Union for Conservation of Nature (IUCN) writes:  http://www.iucn.org/about/union/commissions/cec/?2614/. The Finnish Institute of Environment (SYKE), and Ministry of Environment has a descriptive link:\r\nhttp://www.ymparisto.fi/default.asp?node=5319&lan=en',1),
	(60,-1,1241164122,1241164122,1170,56,2,0,'Info by MauriAhlberg',0,0,3,1241164122,56,0,0,'NatureGate','','http://www.naturegate.net','Online service of wild flowers, trees and bushes, birds, butterflies and later on other organism groups. Fishes will be included during 2009. NatureGateÂ® is result of over 20 years of systematic R&D involving continuing, enlarging and deepening collaboration between professional nature photographers and university experts of the organism groups involved. NatureGateÂ® Online Service uses a patented interactive method and system for fast and easy species identification, based on location of object and its observable chacteristics.',30,1241128800,'Global. The pilot covers currently mainly European species, including invasive species and many cosmopolitan plant species. The ultimate aim is to cover all organism groups and  enlarge to the whole world, use of the patented method and system for interactive object identification using locality and obervable characteristics. Practically, it has to be realized gradually region by region, organism group by organism group. ','Focused on species level biodiversity informatics education for all people, from children to elderly people, both for professionals and amateurs. All organisms are photographed in their natural habitats, biotopes, ecosystems. There are many photos of butterflies and other insects on flowers, pollinating. Photos are of extraordinary quality. They are scientifically accurate and at the same time they creat a strong nature experience. The International Union for Conservation of Nature (IUCN) writes:  http://www.iucn.org/about/union/commissions/cec/?2614/. The Finnish Institute of Environment (SYKE), and Ministry of Environment has a descriptive link:\r\nhttp://www.ymparisto.fi/default.asp?node=5319&lan=en',1),
	(61,-1,1241164225,1241164225,1170,56,3,0,'Info by MauriAhlberg',0,0,4,1241164225,56,0,0,'NatureGate','','http://www.naturegate.net','Online service of wild flowers, trees and bushes, birds, butterflies and later on other organism groups. Fishes will be included during 2009. NatureGateÂ® is result of over 20 years of systematic R&D involving continuing, enlarging and deepening collaboration between professional nature photographers and university experts of the organism groups involved. NatureGateÂ® Online Service uses a patented interactive method and system for fast and easy species identification, based on location of object and its observable chacteristics.',30,1241128800,'Global. The pilot covers currently mainly European species, including invasive species and many cosmopolitan plant species. The ultimate aim is to cover all organism groups and  enlarge to the whole world, use of the patented method and system for interactive object identification using locality and obervable characteristics. NatureGateÂ® will be realized gradually region by region, organism group by organism group. ','Focused on species level biodiversity informatics education for all people, from children to elderly people, both for professionals and amateurs. All organisms are photographed in their natural habitats, biotopes, ecosystems. There are many photos of butterflies and other insects on flowers, pollinating. Photos are of extraordinary quality. They are scientifically accurate and at the same time they creat a strong nature experience. The International Union for Conservation of Nature (IUCN) writes:  http://www.iucn.org/about/union/commissions/cec/?2614/. The Finnish Institute of Environment (SYKE), and Ministry of Environment has a descriptive link:\r\nhttp://www.ymparisto.fi/default.asp?node=5319&lan=en',1),
	(62,-1,1241164270,1241164270,1170,56,4,0,'Info by MauriAhlberg',0,0,5,1241164270,56,0,0,'NatureGate','','http://www.naturegate.net','Online service of wild flowers, trees and bushes, birds, butterflies and later on other organism groups. Fishes will be included during 2009. NatureGateÂ® is result of over 20 years of systematic R&D involving continuing, enlarging and deepening collaboration between professional nature photographers and university experts of the organism groups involved. NatureGateÂ® Online Service uses a patented interactive method and system for fast and easy species identification, based on location of object and its observable chacteristics.',30,1241128800,'Global. The pilot covers currently mainly European species, including invasive species and many cosmopolitan plant species. The ultimate aim is to cover all organism groups and  enlarge to the whole world, use of the patented method and system for interactive object identification using locality and observable characteristics. NatureGateÂ® will be realized gradually region by region, organism group by organism group. ','Focused on species level biodiversity informatics education for all people, from children to elderly people, both for professionals and amateurs. All organisms are photographed in their natural habitats, biotopes, ecosystems. There are many photos of butterflies and other insects on flowers, pollinating. Photos are of extraordinary quality. They are scientifically accurate and at the same time they creat a strong nature experience. The International Union for Conservation of Nature (IUCN) writes:  http://www.iucn.org/about/union/commissions/cec/?2614/. The Finnish Institute of Environment (SYKE), and Ministry of Environment has a descriptive link:\r\nhttp://www.ymparisto.fi/default.asp?node=5319&lan=en',1),
	(63,-1,1241164405,1241164405,1170,56,5,0,'Info by MauriAhlberg',0,0,6,1241164405,56,0,0,'NatureGate','','http://www.naturegate.net','Online service of wild flowers, trees and bushes, birds, butterflies and later on other organism groups. Fishes will be included during 2009. NatureGateÂ® is result of over 20 years of systematic R&D involving continuing, enlarging and deepening collaboration between professional nature photographers and university experts of the organism groups involved. NatureGateÂ® Online Service uses a patented interactive method and system for fast and easy species identification, based on location of object and its observable chacteristics.',30,1241128800,'Global. The pilot covers currently mainly European species, including invasive species and many cosmopolitan plant species. The ultimate aim is to cover all organism groups and  enlarge to the whole world, use of the patented method and system for interactive object identification using locality and observable characteristics. NatureGateÂ® will be realized gradually region by region, organism group by organism group. ','Focused on species level, lifelong, biodiversity informatics education for all people, from children to elderly people, both for professionals and amateurs. All organisms are photographed in their natural habitats, biotopes, ecosystems. There are many photos of butterflies and other insects on flowers, pollinating. Photos are of extraordinary quality. They are scientifically accurate and at the same time they creat a strong nature experience. The International Union for Conservation of Nature (IUCN) writes:  http://www.iucn.org/about/union/commissions/cec/?2614/. The Finnish Institute of Environment (SYKE), and Ministry of Environment has a descriptive link:\r\nhttp://www.ymparisto.fi/default.asp?node=5319&lan=en',1),
	(64,-1,1241164470,1241164470,1170,56,6,0,'Info by MauriAhlberg',0,0,7,1241164470,56,0,0,'NatureGate','','http://www.naturegate.net','Online service of wild flowers, trees and bushes, birds, butterflies and later on other organism groups. Fishes will be included during 2009. NatureGateÂ® is result of over 20 years of systematic R&D involving continuing, enlarging and deepening collaboration between professional nature photographers and university experts of the organism groups involved. NatureGateÂ® Online Service uses a patented interactive method and system for fast and easy species identification, based on location of object and its observable chacteristics.',30,1241128800,'Global. The pilot covers currently mainly European species, including invasive species and many cosmopolitan plant species. The ultimate aim is to cover all organism groups and  enlarge to the whole world, use of the patented method and system for interactive object identification using locality and observable characteristics. NatureGateÂ® will be realized gradually region by region, organism group by organism group. ','Focused on species level, lifelong, biodiversity informatics education for all people, from children to elderly people, both for professionals and amateurs. All organisms are photographed in their natural habitats, biotopes, ecosystems. There are many photos of butterflies and other insects on flowers, pollinating. Photos are of extraordinary quality. They are scientifically accurate and at the same time they create a strong nature experience. The International Union for Conservation of Nature (IUCN) writes:  http://www.iucn.org/about/union/commissions/cec/?2614/. The Finnish Institute of Environment (SYKE), and Ministry of Environment has a descriptive link:\r\nhttp://www.ymparisto.fi/default.asp?node=5319&lan=en',1),
	(65,-1,1241165152,1241165152,1170,56,7,0,'Info by MauriAhlberg',0,0,8,1241165152,56,0,0,'NatureGate','','http://www.naturegate.net','Online service of wild flowers, trees and bushes, birds, butterflies and later on other organism groups. Fishes will be included during 2009. NatureGateÂ® is result of over 20 years of systematic R&D involving continuing, enlarging and deepening collaboration between professional nature photographers and university experts of the organism groups involved. NatureGateÂ® Online Service uses a patented interactive method and system for fast and easy species identification, based on location of object and its observable chacteristics.',30,1241128800,'Global. The pilot covers currently mainly European species, including invasive species and many cosmopolitan plant species. The ultimate aim is to cover all organism groups and  enlarge to the whole world, use of the patented method and system for interactive object identification using locality and observable characteristics. NatureGateÂ® will be realized gradually region by region, organism group by organism group. ','Focused on species level, LIFELONG, BIODIVERSITY informatics EDUCATION for all people, from children to elderly people, both for professionals and amateurs. All organisms are photographed in their natural habitats, biotopes, ecosystems. There are many photos of butterflies and other insects on flowers, pollinating. Photos are of extraordinary quality. They are scientifically accurate and at the same time they create a strong nature experience. The International Union for Conservation of Nature (IUCN) writes:  http://www.iucn.org/about/union/commissions/cec/?2614/. The Finnish Institute of Environment (SYKE), and Ministry of Environment has a descriptive link:\r\nhttp://www.ymparisto.fi/default.asp?node=5319&lan=en\r\n\r\nContact information: \r\nGeneral Director: Producer Eija Lehmuskallio FLS (NatureGate Ltd, partners include University of Helsinki), \r\nemail: eija.lehmuskallio@naturegate.net\r\nResearch Director: Prof. Mauri Ahlberg FLS (University of Helsinki)\r\nemail: mauri.ahlberg@helsinki.fi',1),
	(66,-1,1241278502,1241278502,1170,56,8,0,'Info by MauriAhlberg',0,0,9,1241278502,56,0,0,'NatureGate','','http://www.naturegate.net','Online service of wild flowers, trees and bushes, birds, butterflies and later on other organism groups. Fishes will be included during 2009. NatureGateÂ® is result of over 20 years of systematic R&D involving continuing, enlarging and deepening collaboration between professional nature photographers and university experts of the organism groups involved. NatureGateÂ® Online Service uses a patented interactive method and system for fast and easy species identification, based on location of object and its observable chacteristics.',30,1241128800,'Global. The pilot covers currently mainly European species, including invasive species and many cosmopolitan plant species. The ultimate aim is to cover all organism groups and  enlarge to the whole world, use of the patented method and system for interactive object identification using locality and observable characteristics. NatureGateÂ® will be realized gradually region by region, organism group by organism group. ','Focused on species level, LIFELONG, BIODIVERSITY informatics EDUCATION for all people, from children to elderly people, both for professionals and amateurs. All organisms are photographed in their natural habitats, biotopes, ecosystems. There are many photos of butterflies and other insects on flowers, pollinating. Photos are of extraordinary quality. They are scientifically accurate and at the same time they create a strong nature experience. The International Union for Conservation of Nature (IUCN) writes:  http://www.iucn.org/about/union/commissions/cec/?2614/. The Finnish Institute of Environment (SYKE), and Ministry of Environment has a descriptive link:\r\nhttp://www.ymparisto.fi/default.asp?node=5319&lan=en\r\n\r\nContact information: \r\nExecutive Director: Producer Eija Lehmuskallio FLS (NatureGate Ltd, partners include University of Helsinki), \r\nemail: eija.lehmuskallio@naturegate.net\r\nResearch Director: Prof. Mauri Ahlberg FLS (University of Helsinki)\r\nemail: mauri.ahlberg@helsinki.fi',1),
	(56,917,1248119476,1248119476,1170,56,9,0,'Info by MauriAhlberg',0,0,10,1248119476,56,0,0,'NatureGate','','http://www.naturegate.net','Online service of wild flowers, trees and bushes, birds, butterflies and later on other organism groups. Fishes will be included during 2009. NatureGateÂ® is result of over 20 years of systematic R&D involving continuing, enlarging and deepening collaboration between professional nature photographers and university experts of the organism groups involved. NatureGateÂ® Online Service uses a patented interactive method and system for fast and easy species identification, based on location of object and its observable chacteristics.',30,1241128800,'Global. The pilot covers currently mainly European species, including invasive species and many cosmopolitan plant species. The ultimate aim is to cover all organism groups and  enlarge to the whole world, use of the patented method and system for interactive object identification using locality and observable characteristics. NatureGateÂ® will be realized gradually region by region, organism group by organism group. ','Focused on species level, LIFELONG, BIODIVERSITY informatics EDUCATION for all people, from children to elderly people, both for professionals and amateurs. All organisms are photographed in their natural habitats, biotopes, ecosystems. There are many photos of butterflies and other insects on flowers, pollinating. Photos are of extraordinary quality. They are scientifically accurate and at the same time they create a strong nature experience. The International Union for Conservation of Nature (IUCN) writes:  http://www.iucn.org/about/union/commissions/cec/?2614/. The Finnish Institute of Environment (SYKE), and Ministry of Environment has a descriptive link:\r\nhttp://www.ymparisto.fi/default.asp?contentid=298951&lan=EN\r\n\r\nContact information: \r\nExecutive Director: Producer Eija Lehmuskallio FLS (NatureGate Ltd, partners include University of Helsinki), \r\nemail: eija.lehmuskallio@naturegate.net\r\nResearch Director: Prof. Mauri Ahlberg FLS (University of Helsinki)\r\nemail: mauri.ahlberg@helsinki.fi',1),
	(5,914,1258109964,1258109964,181,5,0,0,'Info by RupertWilson',0,0,0,1258109964,5,0,0,'BG-Base - user list','','http://www.bg-base.com/users.htm','As of February 2009, there are 185 sites in 30 countries using BG-BASE, ranging in size from fewer than 8 staff members to over 400 staff members, and from less than 5 acres (2 ha) to over 3,000 acres (1,215 ha). Users include botanic gardens, arboreta, university campuses, herbaria, museums, libraries, government agencies, research institutions, municipal gardens, conservation organizations, horticultural societies, private estates, zoos, and cemeteries.',30,1258066800,'Global','',1),
	(68,917,1258116816,1258116816,90,0,0,0,'',0,0,0,0,0,0,0,'SouthEast Regional Network of Expertise and Collections','','http://www.sernec.org/','SERNEC is an organization devoted to making the resources of these nearly 222 regional Herbaria of the Southeast available online, in concurrence with developing global standards, so that all available data can then be studied regionally or globally as one virtual, researchable collection. SERNEC will improve access to specimen data of a richly biodiverse ecological environment, and provide a platform for herbarium curators and plant scientists to exchange ideas, share expertise, and benefit from the value of information shared across institutions.',30,1258066800,'Southeast United States of America','',1),
	(69,917,1260898318,1260898318,469,0,0,0,'',0,0,0,0,0,0,0,'Knowledge Network for Biocomplexity','','http://knb.ecoinformatics.org/','The Knowledge Network for Biocomplexity (KNB) is a national network intended to facilitate ecological and environmental research on ecology, biodiversity, and environmental science. For scientists, the KNB is an efficient way to share, discover, access, interpret, integrate and analyze complex ecological data  from a highly-distributed set of field stations, laboratories, research sites, and individual researchers.',30,1535580000,'Global.','',1),
	(70,917,1260898700,1260898700,469,0,0,0,'',0,0,0,0,0,0,0,'DataONE -- Data Observation Network for Earth','','http://dataone.org','The Data Observation Network for Earth (DataONE) transcends domain boundaries to make biological data available from the genome to the ecosystem; makes environmental data available from atmospheric, ecological, hydrological, and oceanographic sources; provides secure and long-term data preservation and access; and engages scientists, land-managers, policy makers, students, educators, and the public. DataONE is a distributed framework and sustainable cyberinfrastructure for open, persistent, robust, and secure access to well-described and easily discovered Earth observational data.',30,1535580000,'Global.','',1),
	(71,917,1282569359,1282569359,1277,0,0,0,'',0,0,0,0,0,0,0,'Tela Botanica','','http://www.tela-botanica.org/','The Tela Botanica network develops botany-related projects in direct collaboration with researchers, professionals and the general public. It contributes to enhancing the knowledge of and facilitates cooperation between players working on plants. The association provides French-speaking botanists with its expertise in facilitating and conducting collaborative projects, as well as in information and communication technologies. Its IT team, with 10 years of experience developing participatory tools, will bolster the reliability and sustainability of this collaborative work.',37,0,'France, Europe','',1),
	(72,917,1299536604,1299536604,81,0,0,0,'',0,0,0,0,0,0,0,'Forestry Education Resources','','http://oedb.org/articles/forestry-education-resources.html','Forestry is the science of studying, managing, and preserving forests. This natural resource provides a home for countless animals and other plants, and they are a vital part of the environment. By studying forestry, scientists can better gauge how they can survive and thrive. The field of forestry also involves growing and nurturing new trees, and developing new forests. This ecosystem is a very integral part of our world, and should be conserved and handled with respect and care.\r\n\r\nThere are links to databases, education, publications, history, organizations and further resources.',30,1299538800,'USA mainly','',1),
	(81,-1,1315409950,1315409950,1453,28,0,0,'Info by ElizabethSellers',0,0,0,1315409950,28,0,0,'NBII Partners','','http://www.nbii.gov/portal/server.pt/community/nbii_partners/','Underpinning the National Biological Information Infrastructure\'s information network is a network of partners. Pages are listed here under the headings of US Federal; State; and Local government; International; Non-profit; Private; University and Multi-sector partners.',30,1182204000,'USA','',1),
	(74,917,1315410201,1315410201,1453,0,0,0,'',0,0,0,0,0,0,0,'United States Virtual Herbarium','','http://www.usvirtualherbarium.org','The United States Virtual Herbarium (USVH) is the primary project of an alliance of United States herbaria, a collaborative effort among herbaria, regional herbarium networks, universities, and other organizations and individuals from across the United States and its territories. The mission of the USVH is to provide, using digital technologies, integrated access to all the plant specimen information in the museums and herbaria of the United States of America.',30,1315346400,'USA','',1),
	(75,917,1334315433,1334315433,1641,0,0,0,'',0,0,0,0,0,0,0,'India Biodiversity Portal','','http://indiabiodiversity.org','Biodiversity Informatics Portal focused on India',30,1334268000,'India','',1),
	(76,917,1334315548,1334315548,1641,0,0,0,'',0,0,0,0,0,0,0,'The Western Ghats Portal','','http://thewesternghats.in','Focused on the biodiversity hotspot of the Western Ghats of India. Funded by the Critical Ecosystems Partnership Fund (CEPF)',30,1334268000,'Western Ghats of India','',1),
	(77,917,1343060087,1343060087,1862,0,0,0,'',0,0,0,0,0,0,0,'GIVD - Global Index of Vegetation-Plot Databases','','http://www.givd.info','GIVD shall provide an overview of exiting vegetation data worldwide, allow researchers to retrieve suitable data to prepare specific research, and thus enhance the awareness and application of this valuable but underestimated source of biodiversity information. Pronouncing the acronym GIVD is intended to remind of the \"gift\" that database hosts offer to the scientific community by facilitating the use of their data by other scientists. \r\nIn GIVD, you find metadata about major vegetation-plot databases of the world. This will help you to retrieve suitable data sources for the analyses you plan and to get into contact with their hosts.',30,0,'Global','',1),
	(78,917,1372674732,1372674732,1984,0,0,0,'',0,0,0,0,0,0,0,'Iberoamerican Infrastructure for Biodiversity Information','','http://www.recibio.net/home-i3b/','The Iberoamerican Infrastructure for Biodiversity Information (I3B) has been developed as a strategic platform for collaboration and scientific communication. Its purpose is to contribute significantly to make the relevant biodiversity information not only available to the scientific community, but useful for the management and sustainable development of the region. Activities are focused on capability (e.g. workshops, distance education platforms, online resources), and on communication and collaboration infrastructure (e.g. website, biodiversity data development and standard adoption, virtual communities) development.\r\nThe consortium gathers together coordination entities for national biodiversity networks --mostly national GBIF nodes-- and leading institutions for the I3B main themes (collections, conservation, data use and analysis and digital documentation). The consortium combines partners with demonstrated ability and experience with others of a high potential for adopting modern methods and tools.\r\nThis network is sponsored by the Ibero-American Programme of Science and Technology for Development, CYTED (http://www.cyted.org/).\r\n',112,1370037600,'17 research groups and 129 researchers from South America (Argentina, Brazil, Chile, Colombia, Costa Rica, Cuba, Ecuador, Mexico, Nicaragua, Uruguay and Venezuela) and Spain work together on the network. Full list of partners and their affiliation: http://www.recibio.net/participantes-i3b/ (in Spanish).','',1),
	(79,917,1376406066,1376406066,2017,0,0,0,'',0,0,0,0,0,0,0,'IrisBG user community','','www.irisbg.com','The community of IrisBG users consists of organizations curating living and/or preserved botanical collections. \r\n\r\nThe community members include academic institutions, botanic gardens, arboreta, zoological gardens, private estates and conservation organizations from around the world.',30,1376344800,'Global','',1),
	(80,917,1380307678,1380307678,40,0,0,0,'',0,0,0,0,0,0,0,'Biodiversity Information Serving Our Nation','','http://bison.usgs.ornl.gov','Biodiversity Information Serving Our Nation (BISON) is a product of the U.S. Geological Survey\'s Core Science Analytics and Synthesis Program. BISON is an information system and mapping application that allows users to access, visualize, explore, and download U.S. species occurrence data from participating data providers.',30,1380232800,'United States of America and its territories.','As of September 2013, BISON includes 110+M species occurrence records and features a collection of developer tools and Web Services which can be used to create custom applications and widgets. BISON is the U.S. Node to the Global Biodiversity Information Facility (GBIF).',1),
	(28,914,1380308203,1380308203,40,28,1,0,'Info by AnnieSimpson',0,0,2,1380308203,28,0,0,'NBII Partners','','','This network was defunded and terminated in January 2012. ',30,1326582000,'USA','The U.S. National Biological Information Infrastructure (NBII) was terminated on 2013-01-15. More information can be found here: http://www.usgs.gov/core_science_systems/Access/p1111-1.html',1),
	(83,-1,1380308969,1380308969,40,82,0,0,'',0,0,0,0,0,0,0,'Global Invasive Species Information Network (GISIN)','','http://www.gisin.org','The GISIN is a virtual network providing a platform to share information about invasive alien species via the Internet and other digital means. It includes a protocol for sharing this specific type of biodiversity information; tutorials; a Globally Unique IDentifier (GUID) registry; and The GISIN List -- a compilation of Internet-accessible databases and information systems that publish information pertaining to invasive, exotic, alien, introduced, non-native species.',30,1380232800,'Global.','The GISIN\'s former URL: http://www.gisinetwork.org',1),
	(82,917,1380309002,1380309002,40,82,0,0,'Info by AnnieSimpson',0,0,0,1380309002,82,0,0,'Global Invasive Species Information Network (GISIN)','','http://www.gisin.org','The GISIN is a virtual network providing a platform to share information about invasive alien species via the Internet and other digital means. It includes a protocol for sharing this specific type of biodiversity information; tutorials; a Globally Unique IDentifier (GUID) registry; and The GISIN List -- a compilation of Internet-accessible databases and information systems that publish information pertaining to invasive, exotic, alien, introduced, non-native species.',30,1380232800,'Global','The GISIN\'s former URL: http://www.gisinetwork.org',1),
	(51,917,1398702487,1398702487,2044,51,0,0,'Info by NestorBeltran',0,0,0,1398702487,51,0,0,'Biodiversity Information System of Colombia (SiB)','','http://www.sibcolombia.net','The Biodiversity Information System of Colombia (SiB Colombia) is a national initiative that aims to provide an facilitate free and open access to biodiversity data. It comprise a network of +100 organisations that work together to ensure that Colombian biodiversity data is available to support education, research and policy for the conservation and sustainable use of our biodiversity.',112,1398636000,'Colombia','',1);

/*!40000 ALTER TABLE `tx_tdwgbiodivprojects_networks` ENABLE KEYS */;
UNLOCK TABLES;



/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
